// meridian-proto catalog harness — renders layouts generated from GRPC SERVICE
// DESCRIPTORS through ViewRenderer + muiKit.
//
// The third producer this kit renders, and the one with the least human input:
//   entry.tsx        hand-authored fixtures, one per primitive
//   studio-entry.tsx real aion graph compositions, projected by meridian-aion-projection
//   proto-entry.tsx  layouts derived from protobuf descriptors alone — nobody wrote
//                    these views; they were recovered from google.api.* annotations
//
// Same `window.meridianHarness.{list,render}` contract as the others, so the existing
// capture + tectonic pipeline renders it unchanged. The bundle is generated by
// meridian-proto's `tests/golden.rs` (the `render-bundle` golden), which means the
// descriptors drawn here are byte-identical to the ones its test suite pins.

import { create, fromJson } from "@bufbuild/protobuf";
import { createElement } from "react";
import { createRoot, type Root } from "react-dom/client";

import { PaletteSchema, ThemeSchema } from "@savvifi/meridian-proto-ts/proto/theme_pb.js";
import { ViewDescriptorSchema } from "@savvifi/meridian-proto-ts/proto/view_pb.js";
import type { RpcInvoker } from "@savvifi/meridian-schemas/uiview";
import { ViewRenderer } from "@savvifi/meridian-web-react";

import { MeridianMuiProvider } from "../src/index.js";
import protoBundle from "./proto-viewdescriptors.json";

const skin = create(ThemeSchema, {
  id: "demo",
  light: create(PaletteSchema, {
    bg: "#ffffff",
    surface: "#ffffff",
    fg: "#1a2027",
    muted: "#5b6b7b",
    border: "#e3e8ee",
    accent: "#2f6f4f",
    accentStrong: "#1f4d37",
  }),
});

interface Entry {
  name: string;
  label: string;
  group: string;
  kind: string;
  view: unknown;
}
const entries = (protoBundle as { entries: Entry[] }).entries;

// Plausible values per column format, so a cell shows something of the right SHAPE.
// This is a structure catalog, not live data — but a table of "Alpha/Bravo" under a
// TIMESTAMP column would misrepresent how the projection actually renders.
const SAMPLES: Record<string, string[]> = {
  STRING: ["alpha", "bravo", "charlie"],
  ENUM_NAME: ["TARGET_STATE_READY", "TARGET_STATE_UNREACHABLE", "TARGET_STATE_READY"],
  INTEGER: ["12", "48", "7"],
  FLOAT_2DP: ["1.50", "12.25", "0.75"],
  TIMESTAMP: ["2026-07-20T09:00:00Z", "2026-07-19T14:30:00Z", "2026-07-18T22:10:00Z"],
  STRING_LIST: ["a, b", "c", "d, e, f"],
};

function sampleFor(format: string | undefined, i: number): string {
  const pool = SAMPLES[format ?? "STRING"] ?? SAMPLES.STRING;
  return pool[i % pool.length];
}

function setNested(target: Record<string, unknown>, path: string, value: unknown): void {
  if (!path) return;
  const keys = path.split(".");
  let cur = target;
  for (let i = 0; i < keys.length - 1; i++) {
    if (typeof cur[keys[i]] !== "object" || cur[keys[i]] === null) cur[keys[i]] = {};
    cur = cur[keys[i]] as Record<string, unknown>;
  }
  cur[keys[keys.length - 1]] = value;
}

interface PanelJson {
  table?: { rowsField?: string; columns?: { fieldPath?: string; format?: string }[] };
  detailHeader?: { titleSourcePath?: string; subtitleSourcePath?: string; statusSourcePath?: string };
  recordCard?: { fields?: { requestField?: string; fieldId?: string }[] };
}
interface ViewJson {
  slots?: { panel?: PanelJson }[];
}

// One invoker serving every panel in the view.
//
// DETAIL views matter here in a way the studio catalog never exercised: a
// DetailHeaderPanel and a RecordCardPanel each `populate` a SINGLE record rather than
// a row list, so an invoker that only answers with `{rowsField: [...]}` renders an
// empty header and a card of blank values — which would look like a projector bug
// when it is really a harness gap.
function buildInvoker(view: ViewJson): RpcInvoker {
  const payload: Record<string, unknown> = { nextCursor: "" };

  for (const slot of view.slots ?? []) {
    const panel = slot.panel;
    if (!panel) continue;

    if (panel.table) {
      const rowsField = panel.table.rowsField || "items";
      const cols = panel.table.columns ?? [];
      payload[rowsField] = [0, 1, 2].map((i) => {
        const row: Record<string, unknown> = {};
        cols.forEach((c) => {
          if (c.fieldPath) setNested(row, c.fieldPath, sampleFor(c.format, i));
        });
        return row;
      });
    }

    // Single-record panels read their fields off the response ROOT.
    for (const path of [
      panel.detailHeader?.titleSourcePath,
      panel.detailHeader?.subtitleSourcePath,
      panel.detailHeader?.statusSourcePath,
    ]) {
      if (path) setNested(payload, path, sampleFor(path.endsWith("state") ? "ENUM_NAME" : "STRING", 0));
    }
    for (const f of panel.recordCard?.fields ?? []) {
      const path = f.requestField || f.fieldId;
      if (path) setNested(payload, path, sampleFor("STRING", 1));
    }
  }

  return { invoke: async () => payload };
}

const byName = new Map(entries.map((e) => [e.name, e]));
let root: Root | undefined;

async function render(name: string): Promise<void> {
  const entry = byName.get(name);
  if (!entry) throw new Error(`unknown meridian-proto view: ${name}`);
  const container = document.getElementById("root");
  if (!container) throw new Error("no #root");
  container.style.background = skin.light?.bg ?? "#fff";
  const view = fromJson(ViewDescriptorSchema, entry.view as never);
  const invoker = buildInvoker(entry.view as ViewJson);
  if (!root) root = createRoot(container);
  root.render(
    createElement(
      MeridianMuiProvider,
      { invoker, theme: skin },
      createElement(ViewRenderer, { view }),
    ),
  );
  await new Promise((r) => setTimeout(r, 250));
}

declare global {
  interface Window {
    meridianHarness: {
      list: () => { name: string; label: string; group: string }[];
      render: (name: string) => Promise<void>;
    };
  }
}

window.meridianHarness = {
  list: () => entries.map((e) => ({ name: e.name, label: e.label, group: e.group })),
  render,
};
