// Studio catalog harness — renders the REAL studio views (projected to meridian
// ViewDescriptors by @savvifi/meridian-aion-projection, full-fidelity via the
// graph install in studio-api) through ViewRenderer + muiKit. Same
// window.meridianHarness.{list,render} contract as entry.tsx, so the existing
// capture + tectonic pipeline renders it unchanged. The ViewDescriptor JSON is
// generated by studio-api/integration-tests/meridian-catalog-export.

import { fromJson } from "@bufbuild/protobuf";
import { createElement } from "react";
import { createRoot, type Root } from "react-dom/client";

import { PaletteSchema, ThemeSchema } from "@savvifi/meridian-proto-ts/proto/theme_pb.js";
import { ViewDescriptorSchema } from "@savvifi/meridian-proto-ts/proto/view_pb.js";
import type { RpcInvoker } from "@savvifi/meridian-schemas/uiview";
import { ViewRenderer } from "@savvifi/meridian-web-react";
import { create } from "@bufbuild/protobuf";

import { MeridianMuiProvider } from "../src/index.js";
import studioBundle from "./studio-viewdescriptors.json";

const skin = create(ThemeSchema, {
  id: "savvi",
  light: create(PaletteSchema, {
    bg: "#ffffff",
    surface: "#ffffff",
    fg: "#1a2027",
    muted: "#5b6b7b",
    border: "#e3e8ee",
    accent: "#2f6f4f",
    accentStrong: "#1f4d37",
  }),
});

// Catalog invoker: returns a few placeholder rows so tables show their columns +
// layout structure (this is a structure/layout catalog, not live data).
const catalogInvoker: RpcInvoker = {
  invoke: async () => ({ items: [{}, {}, {}], products: [{}, {}, {}], rows: [{}, {}, {}], nextCursor: "" }),
};

interface Entry {
  name: string;
  label: string;
  group: string;
  kind: string;
  view: unknown;
}
const entries = (studioBundle as { entries: Entry[] }).entries;

// Studio detail views use host-specific adhoc widgets (headers, workflow panels,
// …). The catalog has no real handlers, so register a labeled placeholder for
// every adhoc handler_id present — honest ("custom widget: X") instead of a
// fallback warning. Handler ids are scraped from the projected ViewDescriptors.
function collectAdhocHandlerIds(): string[] {
  const ids = new Set<string>();
  for (const entry of entries) {
    const slots = (entry.view as { slots?: { panel?: { adhoc?: { handlerId?: string } } }[] }).slots ?? [];
    for (const slot of slots) {
      const id = slot.panel?.adhoc?.handlerId;
      if (id) ids.add(id);
    }
  }
  return [...ids];
}
const adhoc: Record<string, () => ReturnType<typeof createElement>> = {};
for (const id of collectAdhocHandlerIds()) {
  adhoc[id] = () =>
    createElement(
      "div",
      {
        style: {
          padding: 16,
          border: "1px dashed #c4ccd6",
          borderRadius: 8,
          color: "#5b6b7b",
          fontSize: 14,
        },
      },
      `custom widget · ${id}`,
    );
}
const byName = new Map(entries.map((e) => [e.name, e]));
let root: Root | undefined;

async function render(name: string): Promise<void> {
  const entry = byName.get(name);
  if (!entry) throw new Error(`unknown studio view: ${name}`);
  const container = document.getElementById("root");
  if (!container) throw new Error("no #root");
  container.style.background = skin.light?.bg ?? "#fff";
  const view = fromJson(ViewDescriptorSchema, entry.view as never);
  if (!root) root = createRoot(container);
  root.render(
    createElement(
      MeridianMuiProvider,
      { invoker: catalogInvoker, theme: skin, adhoc },
      createElement(ViewRenderer, { view }),
    ),
  );
  await new Promise((r) => setTimeout(r, 250));
}

declare global {
  interface Window {
    meridianHarness: {
      list: () => { name: string; label: string; group: string }[];
      render: (name: string) => Promise<void>;
    };
  }
}

window.meridianHarness = {
  list: () => entries.map((e) => ({ name: e.name, label: e.label, group: e.group })),
  render,
};
