// Screenshot capture — renders every meridian fixture in hermetic Chrome and
// writes a labeled PNG per primitive/layout, plus a LaTeX `figures.tex` fragment.
// Consumed by the rules_tectonic visual catalog. Runs as a js_run_binary build
// action (declared output dir), so the catalog is a pure build artifact.
//
//   argv[2] = @chrome launcher path
//   argv[3] = the harness bundle path
//   argv[4] = output directory (declared out_dir)

const fs = require("node:fs");
const path = require("node:path");
const { chromium } = require("playwright");

// js_run_binary runs from BINDIR; inputs are passed as execroot-relative
// execpaths. Resolve robustly across the plausible bases.
function resolveInput(p) {
  const candidates = [
    path.resolve(p),
    process.env.JS_BINARY__EXECROOT ? path.resolve(process.env.JS_BINARY__EXECROOT, p) : null,
    path.resolve(process.cwd(), "..", "..", "..", p),
  ].filter(Boolean);
  for (const c of candidates) if (fs.existsSync(c)) return c;
  throw new Error(`cannot locate input ${p} (tried: ${candidates.join(", ")})`);
}

// The OUTPUT dir is execroot-relative for the same reason the inputs are, and
// it used to be resolved against the cwd (BINDIR) instead. That was right only
// while mui-kit was its own repository root, where BINDIR-relative "figures"
// and package-relative "figures" are the same directory. After the merge the
// declared outs are packages/mui-kit/figures/... while this wrote to
// <bindir>/figures/... inside the sandbox — so the action exited 0, wrote real
// PNGs, and Bazel then reported all 36 outputs "not created" with NO error
// message anywhere, because nothing had gone wrong as far as this script knew.
function resolveOutput(p) {
  if (path.isAbsolute(p)) return p;
  const execroot = process.env.JS_BINARY__EXECROOT;
  return execroot ? path.resolve(execroot, p) : path.resolve(p);
}

const chromePath = resolveInput(process.argv[2]);
const bundlePath = resolveInput(process.argv[3]);
const outDir = resolveOutput(process.argv[4]);
const bundle = fs.readFileSync(bundlePath, "utf8");
const html =
  '<!doctype html><html><head><meta charset="utf-8"></head>' +
  '<body style="margin:0;background:#eef1f4"><div id="root" style="padding:24px"></div>' +
  "<script>" +
  bundle +
  "</script></body></html>";

function texEscape(s) {
  return s.replace(/[#$%&_{}]/g, (c) => "\\" + c).replace(/~/g, "\\textasciitilde{}");
}

async function main() {
  fs.mkdirSync(outDir, { recursive: true });
  const browser = await chromium.launch({
    executablePath: chromePath,
    headless: true,
    args: ["--disable-dev-shm-usage", "--no-sandbox", "--disable-gpu", "--force-device-scale-factor=2"],
  });
  const figures = [];
  try {
    const context = await browser.newContext({ viewport: { width: 1000, height: 720 } });
    const page = await context.newPage();
    await page.setContent(html, { waitUntil: "load" });
    await page.waitForFunction(() => !!window.meridianHarness, null, { timeout: 15000 });
    const list = await page.evaluate(() => window.meridianHarness.list());

    for (const fixture of list) {
      await page.evaluate((n) => window.meridianHarness.render(n), fixture.name);
      // let async data + paint settle
      await page.waitForTimeout(400);
      const file = `${fixture.name}.png`;
      await page.locator("#root").screenshot({ path: path.join(outDir, file) });
      figures.push({ ...fixture, file });
      console.log("captured", file);
    }
  } finally {
    await browser.close();
  }

  // Emit the LaTeX figure list, grouped, for the catalog to \input.
  const groups = {};
  for (const f of figures) (groups[f.group] ||= []).push(f);
  let tex = "% Generated by tests_browser/capture.js — do not edit.\n";
  for (const group of Object.keys(groups)) {
    tex += `\\section{${texEscape(group)}}\n`;
    for (const f of groups[group]) {
      tex += "\\begin{figure}[H]\\centering\n";
      tex += `\\fbox{\\includegraphics[width=0.9\\textwidth]{${f.file}}}\n`;
      tex += `\\caption{${texEscape(f.label)} \\quad {\\ttfamily ${texEscape(f.name)}}}\n`;
      tex += "\\end{figure}\n\n";
    }
  }
  fs.writeFileSync(path.join(outDir, "figures.tex"), tex);
  console.log(`wrote ${figures.length} figures + figures.tex to ${outDir}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
